version: '3'

services:
  qiandao:
    image: qiandao:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_qiandao$
    volumes:
      - D:\vs2017\Web\Qiandao\Qiandao:/app
      - C:\Users\Mogg\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_qiandao$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_qiandao$ bin/Debug/netcoreapp2.0/Qiandao.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
